import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { AddTask } from '../src/components/AddTask'
import { Task } from '../src/components/Task'


interface ITask {
  id: number,
  task: string
}

const Home: NextPage = () => {

  const [showAdd, setShowAdd] = useState(false)
  const [tasks, setTasks] = useState<ITask[]>([])

  // Set props to pass to the add Component 
  const props = {showAdd, setShowAdd, tasks, setTasks}
  
  // Handle the showAdd State to in value true shows the component add Task
  const handleAdd = () => {
    setShowAdd(true)
  }
  
  const handleDelete = (id:number) => {
    const newList = tasks.filter(task => task.id !== id)
    setTasks(newList)
  }
  

  //Props for task card
  const taskProps = {handleDelete, setShowAdd, showAdd}


  const handleUpdate = (id: number) => {

  }

  useEffect(() => {

    const getTask = JSON.parse(localStorage.getItem('tasks') || "" )
    if(getTask) {
     setTasks(getTask)
     console.log(getTask)
    }

  },[])
 
  useEffect(() => {
    setTimeout(() => {
      localStorage.setItem('tasks', JSON.stringify(tasks)  )
    },500) 
  },[tasks])

  


  return (
    <div className='bg-gray-100 w-full h-screen flex justify-center flex-col items-center'>
      <Head>
        <title>Tradehelm - Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        showAdd ? <AddTask props={props} /> : ""
      }

    <div className='flex justify-center flex-col items-center  w-1/2 '>
      <div className='text-center mb-10'>
        <h1 className='text-6xl font-bold mb-4'>Supermarket list</h1>
        <p className='font-medium'>{tasks?.length} item(s)</p>
      </div>

      <button onClick={handleAdd} className='bg-blue-400 text-white px-80 py-3 text-xl'>Add item</button>
    </div>

    <div className='w-1/2 mt-10 flex flex-col justify-center items-center gap-2'>
      {
        tasks?.map(item => <Task key={Math.random() } item={item} taskProps={taskProps} />)
      }

    </div>
    </div>
  )
}

export default Home
